apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ler3245bq-python
  janus-idp.io/tekton: ler3245bq-python
  backstage.io/kubernetes-id: ler3245bq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ler3245bq-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
