apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ler3245bq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ler3245bq-python 
  name: ler3245bq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ler3245bq-python 
